name: frutiq
description: Vaše digitální zahrada v kapse
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  http: ^1.2.0
  desktop_window: ^0.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # --- TADY PŘIDÁVÁME NÁSTROJ NA GENEROVÁNÍ IKON ---
  flutter_launcher_icons: ^0.13.1 

# --- TADY NÁSTROJI ŘÍKÁME, KDE JE OBRÁZEK A CO S NÍM MÁ DĚLAT ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/Frutiq_icon.png"
  remove_alpha_ios: true # iOS nemá rádo průhledné pozadí, tohle ho případně odstraní

flutter:
  uses-material-design: true
  # --- TADY FLUTTERU ŘÍKÁME, ŽE CHCEME POUŽÍVAT SLOŽKU ASSETS ---
  assets:
    - assets/Frutiq_icon.png