// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTPGn2G4k6Jbpskx5s6RewZI4sBURw_-s',
    appId: '1:418045850760:web:74e9864b4896ecb2575b3d',
    messagingSenderId: '418045850760',
    projectId: 'frutiq-b8729',
    authDomain: 'frutiq-b8729.firebaseapp.com',
    storageBucket: 'frutiq-b8729.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-2pbYAFSL3aDRWbno6G0L3BKUX9xBNw',
    appId: '1:418045850760:android:026424339b02ee5d575b3d',
    messagingSenderId: '418045850760',
    projectId: 'frutiq-b8729',
    storageBucket: 'frutiq-b8729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgw1OW3IcXnmMXMoZM2KnWzzvINplxAc',
    appId: '1:418045850760:ios:7edaf824b933200a575b3d',
    messagingSenderId: '418045850760',
    projectId: 'frutiq-b8729',
    storageBucket: 'frutiq-b8729.firebasestorage.app',
    iosBundleId: 'com.example.frutiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgw1OW3IcXnmMXMoZM2KnWzzvINplxAc',
    appId: '1:418045850760:ios:7edaf824b933200a575b3d',
    messagingSenderId: '418045850760',
    projectId: 'frutiq-b8729',
    storageBucket: 'frutiq-b8729.firebasestorage.app',
    iosBundleId: 'com.example.frutiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTPGn2G4k6Jbpskx5s6RewZI4sBURw_-s',
    appId: '1:418045850760:web:7101e82e46fa8739575b3d',
    messagingSenderId: '418045850760',
    projectId: 'frutiq-b8729',
    authDomain: 'frutiq-b8729.firebaseapp.com',
    storageBucket: 'frutiq-b8729.firebasestorage.app',
  );
}
